import { dispatchAndWait, type McpResult } from "../utils/dispatchAndWait";
import { NODE_TYPES } from "../constants/nodes";
import type { NodeType } from "../types";
import { getGraphState } from "../stores/graphState";

export const GRAPH_EVENTS = {
  ADD_NODE: "graph:add-node",
  ADD_EDGE: "graph:add-edge",
  REMOVE_NODE: "graph:remove-node",
  UPDATE_NODE: "graph:update-node",
  CLEAR: "graph:clear",
  AUTO_LAYOUT: "graph:auto-layout",
} as const;

function slugify(label: string): string {
  return label
    .toLowerCase()
    .replace(/\s+/g, "-")
    .replace(/[^a-z0-9-]/g, "");
}

function err(text: string): McpResult {
  return { content: [{ type: "text", text }], isError: true };
}

async function addNode({ label, nodeType, id }: Record<string, unknown>): Promise<McpResult> {
  const resolvedId = (id as string | undefined) ?? slugify(label as string);
  const resolvedType = NODE_TYPES.includes(nodeType as NodeType) ? (nodeType as NodeType) : "service";
  if (getGraphState().nodes.find((n) => n.id === resolvedId)) return err(`Error: node "${resolvedId}" already exists.`);
  return dispatchAndWait(
    GRAPH_EVENTS.ADD_NODE,
    { id: resolvedId, label, nodeType: resolvedType },
    JSON.stringify({ id: resolvedId, label, nodeType: resolvedType }),
  );
}

export const addNodeTool = {
  name: "add_node",
  description:
    "Add a new node to the diagram. Returns the assigned node id — save it to use in add_edge calls. " +
    "If no id is provided, it is auto-generated by lowercasing the label and replacing spaces with hyphens (e.g. 'API Gateway' → 'api-gateway'). " +
    "Call this before add_edge — edges require existing node ids. " +
    "Choose nodeType based on the technology: use 'database' for SQL/NoSQL stores (Postgres, MongoDB), " +
    "'cache' for in-memory stores (Redis, Memcached), 'queue' for message brokers (RabbitMQ, Kafka), " +
    "'api' for API gateways or reverse proxies, 'client' for end users or frontends, 'service' for everything else.",
  inputSchema: {
    type: "object",
    properties: {
      label: { type: "string", description: "Human-readable display name shown on the node, e.g. 'Auth Service'" },
      nodeType: {
        type: "string",
        enum: NODE_TYPES,
        description:
          "Visual category: 'service' (backend microservice), 'database' (persistent storage), " +
          "'cache' (in-memory store), 'queue' (message broker), 'api' (gateway/proxy), 'client' (user/frontend)",
      },
      id: {
        type: "string",
        description:
          "Optional stable identifier used in add_edge. If omitted, auto-derived from label (lowercase, spaces → hyphens). " +
          "Provide explicitly when the label contains special characters or you need a predictable id.",
      },
    },
    required: ["label"],
  },
  outputSchema: {
    type: "object",
    properties: {
      id: { type: "string", description: "The assigned node id to use in subsequent add_edge calls." },
      label: { type: "string" },
      nodeType: { type: "string" },
    },
    required: ["id", "label", "nodeType"],
  },
  annotations: { readOnlyHint: "false" },
  execute: addNode,
};

async function addEdge({ source, target, label }: Record<string, unknown>): Promise<McpResult> {
  const { nodes, edges } = getGraphState();
  const src = source as string;
  const tgt = target as string;
  if (!nodes.find((n) => n.id === src)) return err(`Error: source node "${src}" not found.`);
  if (!nodes.find((n) => n.id === tgt)) return err(`Error: target node "${tgt}" not found.`);
  if (edges.find((e) => e.source === src && e.target === tgt))
    return err(`Error: edge "${src} → ${tgt}" already exists.`);
  return dispatchAndWait(GRAPH_EVENTS.ADD_EDGE, { source: src, target: tgt, label }, `Edge created: ${src} → ${tgt}`);
}

export const addEdgeTool = {
  name: "add_edge",
  description:
    "Draw a directed edge from one node to another. Both nodes must already exist — call add_node first. " +
    "Use the node id returned by add_node (or the auto-generated id) as source and target. " +
    "Call get_graph if you are unsure which node ids are currently in the diagram.",
  inputSchema: {
    type: "object",
    properties: {
      source: { type: "string", description: "ID of the source (origin) node" },
      target: { type: "string", description: "ID of the target (destination) node" },
      label: { type: "string", description: "Optional short label shown on the edge, e.g. 'HTTP', 'gRPC', 'SQL'" },
    },
    required: ["source", "target"],
  },
  outputSchema: {
    type: "string",
    description: "A message confirming the edge was created or describing the error.",
  },
  annotations: { readOnlyHint: "false" },
  execute: addEdge,
};

async function removeNode({ id }: Record<string, unknown>): Promise<McpResult> {
  const nodeId = id as string;
  if (!getGraphState().nodes.find((n) => n.id === nodeId)) return err(`Error: node "${nodeId}" not found.`);
  return dispatchAndWait(GRAPH_EVENTS.REMOVE_NODE, { id: nodeId }, `Removed node "${nodeId}" and its edges.`);
}

export const removeNodeTool = {
  name: "remove_node",
  description:
    "Remove a node by id. All edges connected to it are automatically removed as well. Use get_graph to find the correct id before calling this.",
  inputSchema: {
    type: "object",
    properties: {
      id: { type: "string", description: "ID of the node to remove" },
    },
    required: ["id"],
  },
  outputSchema: {
    type: "string",
    description: "A message confirming removal or describing the error.",
  },
  annotations: { readOnlyHint: "false" },
  execute: removeNode,
};

async function updateNode({ id, label, nodeType }: Record<string, unknown>): Promise<McpResult> {
  const nodeId = id as string;
  if (!getGraphState().nodes.find((n) => n.id === nodeId)) return err(`Error: node "${nodeId}" not found.`);
  return dispatchAndWait(GRAPH_EVENTS.UPDATE_NODE, { id: nodeId, label, nodeType }, `Updated node "${nodeId}".`);
}

export const updateNodeTool = {
  name: "update_node",
  description:
    "Update the label or nodeType of an existing node. The node id stays the same. Use get_graph to confirm the id before calling.",
  inputSchema: {
    type: "object",
    properties: {
      id: { type: "string", description: "ID of the node to update" },
      label: { type: "string", description: "New display label" },
      nodeType: { type: "string", enum: NODE_TYPES, description: "New node type" },
    },
    required: ["id"],
  },
  outputSchema: {
    type: "string",
    description: "A message confirming the update or describing the error.",
  },
  annotations: { readOnlyHint: "false" },
  execute: updateNode,
};

function getGraph(): McpResult {
  return { content: [{ type: "text", text: JSON.stringify(getGraphState(), null, 2) }] };
}

export const getGraphTool = {
  name: "get_graph",
  description:
    "Returns all current nodes and edges. Call this when you need to know existing node ids before calling add_edge, remove_node, or update_node.",
  inputSchema: { type: "object", properties: {} },
  outputSchema: {
    type: "object",
    properties: {
      nodes: {
        type: "array",
        items: {
          type: "object",
          properties: {
            id: { type: "string" },
            label: { type: "string" },
            nodeType: { type: "string" },
          },
          required: ["id", "label", "nodeType"],
        },
      },
      edges: {
        type: "array",
        items: {
          type: "object",
          properties: {
            source: { type: "string" },
            target: { type: "string" },
            label: { type: "string" },
          },
          required: ["source", "target"],
        },
      },
    },
    required: ["nodes", "edges"],
  },
  annotations: { readOnlyHint: "true" },
  execute: getGraph,
};

export async function clearGraph(): Promise<McpResult> {
  return dispatchAndWait(GRAPH_EVENTS.CLEAR, {}, "Graph cleared.");
}

export const clearGraphTool = {
  name: "clear_graph",
  description:
    "Remove all nodes and edges from the diagram. Use only when the user explicitly asks to reset or start over.",
  inputSchema: { type: "object", properties: {} },
  outputSchema: { type: "string", description: "A message confirming the graph was cleared." },
  annotations: { readOnlyHint: "false" },
  execute: clearGraph,
};

export async function autoLayout(): Promise<McpResult> {
  return dispatchAndWait(GRAPH_EVENTS.AUTO_LAYOUT, {}, "Layout applied.");
}

export const autoLayoutTool = {
  name: "auto_layout",
  description:
    "Rearrange all nodes into a readable left-to-right layered layout based on edge directions. " +
    "Only call this when the user explicitly asks to arrange, organize, or layout the diagram. " +
    "Do not call it automatically after adding nodes or edges.",
  inputSchema: { type: "object", properties: {} },
  outputSchema: { type: "string", description: "A message confirming the layout was applied." },
  annotations: { readOnlyHint: "false" },
  execute: autoLayout,
};

export const graphTools = [
  addNodeTool,
  addEdgeTool,
  removeNodeTool,
  updateNodeTool,
  getGraphTool,
  clearGraphTool,
  autoLayoutTool,
];
